name: Test

on:
  push:
  pull_request:

# Testing that the tests still pass... They seem to with git version 2.37.1 (Apple Git-137.1), but not with git version 2.39.2 (Apple Git-143)

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # The tests assume all commits are available
      - name: Run tests
        run: |
          make tests | tee .tests-summary.txt
          grep "All tests passed." .tests-summary.txt || exit 1
